# Generated by Django 6.0.5 on 2026-05-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_pago_metodo_pago_orden_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='unidades',
            field=models.IntegerField(default=0),
        ),
    ]
