# Generated by Django 6.0.5 on 2026-05-30 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_orden_unidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='producto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
    ]
