# Generated by Django 6.0.5 on 2026-05-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_orden_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='documento_cliente',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
