# Generated by Django 6.0.5 on 2026-05-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_orden_documento_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
