# Generated by Django 6.0.5 on 2026-06-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_pago_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='token_dispensar',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
